### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by sam-shervin** [ComputerSocietyVITC/bitwars-24#38]
underlines for headings and use high quality vit logo. Alignment should be done properly. responsive is nice already

**Comment by a2ys** [comment]
#42 addresses this.

**Comment by sam-shervin** [comment]
<img width="1710" alt="image" src="https://github.com/user-attachments/assets/0f9cc602-b727-4375-ae0d-174091c8af2a">
can be aligned better

**Comment by sam-shervin** [comment]
@a2ys footer responsiveness has to be reworked

**Comment by a2ys** [comment]
> <img width="1710" alt="image" src="https://github.com/user-attachments/assets/0f9cc602-b727-4375-ae0d-174091c8af2a">
> can be aligned better
> 

Oh okay okay, I thought you said mobile screen alignment. And okay, I'll work more on the responsiveness.

**Comment by a2ys** [comment]
#53
